version: '3'

services:
  fastfeet-api:
    build: .
    container_name: fastfeet-api
    volumes:
      - .:/home/node/api
      - /home/node/api/node_modules
    environment:
      - APP_SECRET=${APP_SECRET}
    ports:
      - '3333:3333'
    command: yarn start
    depends_on:
      - fast-database
      - redisfastfeet

  fast-database:
    image: postgres:11
    ports:
      - '5432:5432'
    container_name: fast-database
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    volumes:
      - fast-database-data:/data

  redisfastfeet:
    image: redis:alpine
    container_name: redisfastfeet
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}

volumes:
  fast-database-data:
