version: '3'

services:

  fast-database:
    image: postgres:11
    ports:
      - '5432:5432'
    container_name: fast-database
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    volumes:
      - fast-database-data:/data

  redisfastfeet:
    image: redis:alpine
    container_name: redisfastfeet
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}

volumes:
  fast-database-data:
